name: looplab
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  path: ^1.9.0
  path_provider: ^2.1.4
  sembast: ^3.7.3+3

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

fonts:
  - family: RadixIcons
    fonts:
      - asset: "packages/shadcn_flutter/icons/RadixIcons.otf"
  - family: "GeistSans"
    fonts:
      - asset: "packages/shadcn_flutter/fonts/Geist-Black.otf"
        weight: 800
      - asset: "packages/shadcn_flutter/fonts/Geist-Bold.otf"
        weight: 700
      - asset: "packages/shadcn_flutter/fonts/Geist-Light.otf"
        weight: 300
      - asset: "packages/shadcn_flutter/fonts/Geist-Medium.otf"
        weight: 500
      - asset: "packages/shadcn_flutter/fonts/Geist-SemiBold.otf"
        weight: 600
      - asset: "packages/shadcn_flutter/fonts/Geist-Thin.otf"
        weight: 100
      - asset: "packages/shadcn_flutter/fonts/Geist-UltraBlack.otf"
        weight: 900
      - asset: "packages/shadcn_flutter/fonts/Geist-UltraLight.otf"
        weight: 200
      - asset: "packages/shadcn_flutter/fonts/Geist-Regular.otf"
        weight: 400
  - family: "GeistMono"
    fonts:
      - asset: "packages/shadcn_flutter/fonts/GeistMono-Black.otf"
        weight: 800
      - asset: "packages/shadcn_flutter/fonts/GeistMono-Bold.otf"
        weight: 700
      - asset: "packages/shadcn_flutter/fonts/GeistMono-Light.otf"
        weight: 300
      - asset: "packages/shadcn_flutter/fonts/GeistMono-Medium.otf"
        weight: 500
      - asset: "packages/shadcn_flutter/fonts/GeistMono-Regular.otf"
        weight: 400
      - asset: "packages/shadcn_flutter/fonts/GeistMono-SemiBold.otf"
        weight: 600
      - asset: "packages/shadcn_flutter/fonts/GeistMono-Thin.otf"
        weight: 100
      - asset: "packages/shadcn_flutter/fonts/GeistMono-UltraBlack.otf"
        weight: 900
      - asset: "packages/shadcn_flutter/fonts/GeistMono-UltraLight.otf"
        weight: 200
