name: repeatlab
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  # audio_waveforms: ^1.0.5
  bloc: ^8.1.4
  change_app_package_name: ^1.4.0
  dart_mappable: ^4.3.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_soloud:
    ^2.1.7
    # git:
    #   url: https://github.com/alnitak/flutter_soloud.git
    #   ref: feat_waveform
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lint: ^2.3.0
  lottie: ^3.2.0
  package_info_plus: ^8.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  sembast: ^3.8.0
  uuid: ^4.5.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/images/
