name: repeatlab
description: Audio loop studio
version: 1.0.2+15
publish_to: none

environment:
  flutter: 3.27.2
  sdk: ^3.5.0

dependencies:
  # audio_waveforms: ^1.0.5
  alchemist: ^0.11.0
  audioplayers: ^6.0.0
  # audiotags: ^1.4.3
  bloc: ^9.0.0
  change_app_package_name: ^1.4.0
  dart_mappable: ^4.3.0
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  # flutter_launcher_icons: ^0.14.2
  flutter_localizations:
    sdk: flutter
  flutter_soloud: ^2.1.7

  # google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  in_app_review: ^2.0.10
  intl: ^0.19.0
  lint: ^2.3.0
  lottie: ^3.3.1
  package_info_plus: ^8.1.3
  path: ^1.9.0
  path_provider: ^2.1.4
  purchases_flutter: ^8.4.1
  purchases_ui_flutter: ^8.4.1
  sembast: ^3.8.0
  sentry_flutter: ^8.12.0
  shared_preferences: ^2.3.5
  tutorial_coach_mark: ^1.2.12
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  wiredash: ^2.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.12
  dart_mappable_builder: ^4.3.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  # flutter_launcher_icons: ^0.14.3
  # flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Nunito Sans
      fonts:
        - asset: assets/fonts/NunitoSans_7pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/NunitoSans_7pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/NunitoSans_7pt-Light.ttf
          weight: 300
        - asset: assets/fonts/NunitoSans_7pt-Italic.ttf
          weight: 400
          style: italic
    - family: Oswald
      fonts:
        - asset: assets/fonts/Oswald-Regular.ttf
          weight: 400
        - asset: assets/fonts/Oswald-Bold.ttf
          weight: 700
        - asset: assets/fonts/Oswald-Light.ttf
          weight: 300
