name: repeatlab

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  semantic-pull-request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1
    if: github.event_name == 'pull_request'

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install FVM
        run: dart pub global activate fvm
      - name: Install Flutter via FVM
        run: fvm install
      - name: Install dependencies
        run: fvm flutter pub get
      - name: Analyze project
        run: fvm flutter analyze --fatal-infos

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install FVM
        run: dart pub global activate fvm
      - name: Install Flutter via FVM
        run: fvm install
      - name: Install dependencies
        run: fvm flutter pub get
      - name: Run tests
        run: fvm flutter test
